### ISSUE TITLE
Unable to add cube

### ISSUE THREAD

**Issue by chinswain** [TedTolboom/com.xiaomi-mi-zigbee#36]
Just tried adding the cube, add device wizard reports no device found, debug from cli install\run:

`2018-01-27 00:10:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [0] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: forced_timeout
(node:2538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-01-27 00:10:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [1] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
2018-01-27 00:10:24 [err] [ManagerDrivers] [sensor_switch] [0] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_32768 { Error: Invalid cluster or attr
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'Invalid cluster or attr' }
2018-01-27 00:10:24 [err] [ManagerDrivers] [sensor_motion.aq2] [0] registerAttrReportListener() -> error could not configure attrReport_0_msOccupancySensing_occupancy { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: forced_timeout
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Invalid cluster or attr
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: forced_timeout
2018-01-27 00:10:54 [err] [ManagerDrivers] [sensor_motion.aq2] [1] registerAttrReportListener() -> error could not configure attrReport_0_msOccupancySensing_occupancy { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: forced_timeout
2018-01-27 00:10:54 [err] [ManagerDrivers] [weather] [0] registerAttrReportListener() -> error could not configure attrReport_0_msTemperatureMeasurement_measuredValue { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: forced_timeout
2018-01-27 00:10:54 [err] [ManagerDrivers] [sensor_switch] [0] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: forced_timeout
2018-01-27 00:10:54 [err] [ManagerDrivers] [sensor_motion.aq2] [0] registerAttrReportListener() -> error could not configure attrReport_0_msIlluminanceMeasurement_measuredValue { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: forced_timeout
2018-01-27 00:11:24 [err] [ManagerDrivers] [sensor_motion.aq2] [1] registerAttrReportListener() -> error could not configure attrReport_0_msIlluminanceMeasurement_measuredValue { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: forced_timeout
2018-01-27 00:11:24 [err] [ManagerDrivers] [weather] [0] registerAttrReportListener() -> error could not configure attrReport_0_msRelativeHumidity_measuredValue { Error: forced_timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'forced_timeout' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: forced_timeout
2018-01-27 00:11:24 [err] [ManagerDrivers] [weather] [0] registerAttrReportListener() -> error could not configure attrReport_0_msPressureMeasurement_16 { Error: Invalid cluster or attr
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1245)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1143)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'Invalid cluster or attr' }
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Invalid cluster or attr`

**Comment by chinswain** [comment]
Issue resolved - cube requires multiple button presses to keep it alive (same as the older devices)

**Comment by TedTolboom** [comment]
Thanks for reporting; updated the hints for the Cube accordingly
